[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
clap = "3.2"
fxhash = "0.2"
json = { package = "json5", version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
zip = "0.6"
