[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../base" }
core_client = { path = "../core_client" }
render = { package = "render_wgpu", path = "../render_wgpu" }
image = { version = "0.24", default-features = false, features = ["png"] }
