[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.9", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
